### ISSUE TITLE
how to include the library directly in the browser?

### ISSUE THREAD

**Issue by waldenn** [semi-technologies/weaviate-javascript-client#40]
Hi, Thanks for this interesting semweb framework!

Any tips on how to include this library directly in the browser (without the "require" build step)?
I could not find a bundled "dist" build, just the "lib.js" - which does not work when loaded directly in the browser.

**Comment by bobvanluijt** [comment]
Thanks @waldenn – thanks :)

This is actually something that was discussed [here](https://github.com/semi-technologies/weaviate-javascript-client/issues/35) as well. I'll tag you and close this one
