### ISSUE TITLE
Support of Weaviate 1.14.1 still missing (in referencesBatcher)?

### ISSUE THREAD

**Issue by erikvullings** [semi-technologies/weaviate-javascript-client#76]
I'm using Weaviate 1.14.1, and when I want to use the batch API to add cross references, I get the following error:

`Usage of beacons paths with className is not supported in Weaviate . className parameter is ignored`

Is the `referencesBatcher` not yet updated to support 1.14?

**Comment by etiennedi** [comment]
Thanks for the report. It should be supported, we'll look into it.

**Comment by antas-marcin** [comment]
Hello @erikvullings we have released `2.11.1` version of `JS` client which should fix this issue.

**Comment by erikvullings** [comment]
Thanks for the quick response: it is fixed now!
